version: 0.0
os: linux 
files:
  - source: source 
    destination: /var/www/loadtest/src
  - object: /var/www/loadtest/src
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
