version: 0.0
os: linux 
files:
  - source: / 
    destination: /var/www/loadtest/src
permission:
  - object: /var/www/loadtest/src/AppBundle
    pattern: "*"
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
  - object: /var/www/loadtest/src/Appbundle/Controller
    pattern: "*"
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
  - object: /var/www/loadtest/src/Appbundle/Controller/Tests
    pattern: "*"
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
  - object: /var/www/loadtest/src/Appbundle/Controller/Tests/Controller
    pattern: "*"
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
  - object: /var/www/loadtest/src/Appbundle/Controller/Test
    pattern: "*"
    mode: 644
    owner: nginx
    group: nginx
    type:
      - directory
  - object: /var/www/loadtest/src/Appbundle/Controller/Test/DefaultControllerTest.php
    pattern: "*"
    mode: 755
    owner: nginx
    group: nginx
    type:
      - file
  - object: /var/www/loadtest/src/Appbundle/Controller/DefaultController.php
    pattern: "*"
    mode: 755
    owner: nginx
    group: nginx
    type:
      - file
  - object: /var/www/loadtest/src/Appbundle/AppBundle.php
    pattern: "*"
    mode: 755
    owner: nginx
    group: nginx
    type:
      - file
  - object: /var/www/loadtest/src/appspec.yml
    pattern: "*"
    mode: 755
    owner: nginx
    group: nginx
    type:
      - file
